
url: "https://username.github.io"
baseurl: "/sblog"  # Project site base URL
paths:
  css: "/assets/css"
  js: "/assets/js"
  images: "/assets/images"collections:
  authors:

  plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

  excerpt_separator: "<!--excerpt-->"